"""Add embedded_line field to GoogleCalendarAuth model

Revision ID: 11ea24239030
Revises: 
Create Date: 2025-09-02 05:46:35.665861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ea24239030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_calendar_auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embeded_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_calendar_auth', schema=None) as batch_op:
        batch_op.drop_column('embeded_link')

    # ### end Alembic commands ###
