"""initial schema

Revision ID: c9a6910c93ea
Revises: 
Create Date: 2025-09-03 04:58:54.508406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9a6910c93ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('res_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('image_file', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('twilio_account_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_auth_token', sa.String(length=255), nullable=True),
    sa.Column('twilio_phone_number', sa.String(length=20), nullable=True),
    sa.Column('deepgram_api_key', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('callsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('call_sid', sa.String(length=64), nullable=False),
    sa.Column('stream_sid', sa.String(length=64), nullable=True),
    sa.Column('recording_sid', sa.String(length=64), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('from_number', sa.String(length=32), nullable=True),
    sa.Column('to_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['res_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('callsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callsession_call_sid'), ['call_sid'], unique=True)
        batch_op.create_index(batch_op.f('ix_callsession_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_callsession_from_number'), ['from_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_callsession_recording_sid'), ['recording_sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_callsession_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_callsession_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_callsession_stream_sid'), ['stream_sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_callsession_to_number'), ['to_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_callsession_user_id'), ['user_id'], unique=False)

    op.create_table('google_calendar_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('credentials_json', sa.Text(), nullable=True),
    sa.Column('token_json', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('calendar_id', sa.String(length=255), nullable=True),
    sa.Column('time_zone', sa.String(length=100), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('embeded_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['res_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_calendar_auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_calendar_auth_user_id'), ['user_id'], unique=False)

    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('callsession_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_link', sa.String(length=500), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('audio_data', sa.LargeBinary(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=32), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['callsession_id'], ['callsession.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['res_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_callsession_id'), ['callsession_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_appointment_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_user_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_callsession_id'))

    op.drop_table('appointment')
    with op.batch_alter_table('google_calendar_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_calendar_auth_user_id'))

    op.drop_table('google_calendar_auth')
    with op.batch_alter_table('callsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callsession_user_id'))
        batch_op.drop_index(batch_op.f('ix_callsession_to_number'))
        batch_op.drop_index(batch_op.f('ix_callsession_stream_sid'))
        batch_op.drop_index(batch_op.f('ix_callsession_status'))
        batch_op.drop_index(batch_op.f('ix_callsession_started_at'))
        batch_op.drop_index(batch_op.f('ix_callsession_recording_sid'))
        batch_op.drop_index(batch_op.f('ix_callsession_from_number'))
        batch_op.drop_index(batch_op.f('ix_callsession_expires_at'))
        batch_op.drop_index(batch_op.f('ix_callsession_call_sid'))

    op.drop_table('callsession')
    op.drop_table('res_user')
    # ### end Alembic commands ###
