"""Builtin industry profile specs."""

from __future__ import annotations

from app.industries.types import (
    ConfirmationPolicy,
    DepositPolicy,
    HandoffPolicy,
    IndustryProfileSpec,
    IndustryType,
    PrivacyPolicy,
)

PROFILE_CATALOG: dict[IndustryType, IndustryProfileSpec] = {
    "clinic": IndustryProfileSpec(
        industry_type="clinic",
        scheduling_mode="multi_resource",
        required_customer_fields=["name", "phone"],
        required_booking_fields=[
            "visit_type",
            "location",
            "start_datetime",
            "explicit_confirmation",
        ],
        enabled_tools=[
            "find_visit_types",
            "find_practitioners",
            "appointment_availability",
            "create_appointment",
            "reschedule_appointment",
            "cancel_appointment",
            "request_human_handoff",
            "join_waitlist",
        ],
        confirmation_policy=ConfirmationPolicy(
            require_explicit_confirm=True,
            send_reminders=True,
            send_forms=True,
            send_instructions=True,
        ),
        handoff_policy=HandoffPolicy(enabled=True, emergency_escalation=True),
        privacy_policy=PrivacyPolicy(
            redact_medical_from_analytics=True,
            redact_medical_from_logs=True,
            allow_diagnosis_advice=False,
            store_clinical_notes=False,
            compliance_claimed=False,
        ),
        terminology={
            "reservation": "appointment",
            "resource": "practitioner",
            "service": "visit type",
        },
        flow_steps=[
            "intent",
            "emergency_safety_gate",
            "administrative_appointment_intent",
            "minimal_identity",
            "specialty_visit_type",
            "location",
            "practitioner_preference",
            "pre_visit_questions",
            "availability",
            "explicit_confirmation",
            "appointment",
            "reminders_forms_instructions",
        ],
        resource_types=["practitioner", "room", "equipment"],
        capabilities=[
            "specialty",
            "visit_type",
            "referral_requirement",
            "waitlist",
            "ehr_port",
        ],
        metadata={"forbid_diagnosis": True, "ehr_required": False},
    ),
    "restaurant": IndustryProfileSpec(
        industry_type="restaurant",
        scheduling_mode="capacity",
        required_customer_fields=["name", "phone"],
        required_booking_fields=["date", "time", "party_size", "location"],
        enabled_tools=[
            "catalog_search",
            "restaurant_availability",
            "create_reservation",
            "modify_reservation",
            "cancel_reservation",
            "join_waitlist",
            "promote_waitlist",
            "request_human_handoff",
        ],
        confirmation_policy=ConfirmationPolicy(require_explicit_confirm=True),
        deposit_policy=DepositPolicy(enabled=False),
        handoff_policy=HandoffPolicy(enabled=True),
        privacy_policy=PrivacyPolicy(),
        terminology={
            "reservation": "reservation",
            "resource": "table",
            "service": "dining",
        },
        flow_steps=[
            "date",
            "time",
            "party_size",
            "location",
            "availability_capacity",
            "alternatives",
            "seating_preference",
            "customer_contact",
            "dietary_accessibility_notes",
            "optional_deposit",
            "confirmation",
        ],
        resource_types=["table", "dining_area", "capacity_pool"],
        capabilities=[
            "party_size",
            "turn_duration",
            "seating_preference",
            "deposit_policy",
            "waitlist",
            "capacity_allocation",
        ],
        metadata={"sync_calendar": False, "use_capacity_engine": True},
    ),
    "salon": IndustryProfileSpec(
        industry_type="salon",
        scheduling_mode="multi_resource",
        required_customer_fields=["name", "phone"],
        required_booking_fields=["service", "start_datetime"],
        enabled_tools=[
            "find_salon_services",
            "find_available_staff",
            "find_salon_availability",
            "estimate_service_price",
            "book_salon_service",
            "modify_salon_booking",
            "cancel_appointment",
            "request_human_handoff",
        ],
        confirmation_policy=ConfirmationPolicy(require_explicit_confirm=True),
        handoff_policy=HandoffPolicy(enabled=True),
        privacy_policy=PrivacyPolicy(),
        terminology={
            "reservation": "appointment",
            "resource": "stylist",
            "service": "service",
        },
        flow_steps=[
            "service",
            "add_ons",
            "optional_staff_preference",
            "required_capabilities_resources",
            "time_slots",
            "price",
            "confirmation",
        ],
        resource_types=["employee", "chair", "equipment"],
        capabilities=["skills", "staff", "equipment", "buffers", "add_ons", "multi_step_duration"],
        metadata={"support_addons": True},
    ),
    "general": IndustryProfileSpec(
        industry_type="general",
        scheduling_mode="single_resource",
        required_customer_fields=["name"],
        required_booking_fields=["start_datetime"],
        enabled_tools=[
            "search_catalog",
            "get_price",
            "create_quote_request",
            "book_appointment",
            "take_message",
            "check_order_status",
            "request_human_handoff",
            "answer_faq",
            "provide_product_information",
            "send_secure_link",
        ],
        confirmation_policy=ConfirmationPolicy(require_explicit_confirm=False),
        handoff_policy=HandoffPolicy(enabled=True),
        privacy_policy=PrivacyPolicy(),
        terminology={
            "reservation": "appointment",
            "resource": "calendar",
            "service": "service",
        },
        flow_steps=[
            "intent",
            "qualify_or_answer",
            "book_or_message",
            "confirmation",
        ],
        resource_types=[],
        capabilities=[
            "book_appointment",
            "answer_faq",
            "provide_product_information",
            "provide_price",
            "qualify_lead",
            "take_message",
            "request_quote",
            "check_order_status",
            "human_transfer",
            "send_secure_payment_product_link",
        ],
        metadata={},
    ),
}


def get_profile_spec(industry_type: IndustryType | str) -> IndustryProfileSpec:
    key = str(industry_type).strip().casefold()
    if key not in PROFILE_CATALOG:
        raise ValueError(f"unknown industry_type: {industry_type}")
    return PROFILE_CATALOG[key]  # type: ignore[index]
